jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 120
  pool:
    vmImage: ${{ parameters.vmImage }}
  strategy:
    matrix:
      stack-def:
        BUILD: stack
        STACK_YAML: stack.yaml
        DEPLOY: 1
      stack-lts-16:
        BUILD: stack
        STACK_YAML: stack.yaml
      nightly:
        BUILD: stack
        ARGS: "--resolver nightly"
    maxParallel: 4
  steps:
  - bash: echo "##vso[task.setvariable variable=TAG]${BUILD_SOURCEBRANCH##refs/tags/}"
    displayName: Set TAG variable
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
  - script: |
      export STACK_ROOT="$(Build.SourcesDirectory)"/.stack-root;
      mkdir -p ~/.local/bin
      curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      case "$BUILD" in
        style)
          PACKAGE=hlint
          echo "Downloading $PACKAGE now ..."

          RELEASES=$(curl --silent https://github.com/ndmitchell/$PACKAGE/releases)
          URL=https://github.com/$(echo "$RELEASES" | grep -o '\"[^\"]*-x86_64-linux\.tar\.gz\"' | sed s/\"//g | head -n1)
          VERSION=$(echo "$URL" | sed -e 's/.*-\([\.0-9]\+\)-x86_64-linux\.tar\.gz/\1/')

          curl --progress-bar --location -o"$PACKAGE.tar.gz" "$URL"
          tar -xzf "$PACKAGE.tar.gz" -C .
          mv "$PACKAGE-$VERSION" "$PACKAGE"
          export PATH="$(pwd)"/hlint:$PATH
          ;;
        *)
          export PATH=$HOME/.local/bin:$PATH
          stack --install-ghc $ARGS test --bench --only-dependencies
          ;;
      esac
      set -ex
      case "$BUILD" in
        style)
          hlint src/
          ;;
        *)
          stack $ARGS test --bench --no-run-benchmarks --haddock --no-haddock-deps
          ;;
      esac
      set +ex
    env:
      OS_NAME: ${{ parameters.os }}
    displayName: 'Installation ${{parameters.os}} & Test'
  - task: ArchiveFiles@2
    inputs:
      includeRootFolder: false
      archiveType: tar
      tarCompression: gz
      archiveFile: $(Build.ArtifactStagingDirectory)/tldr-linux-$(TAG).tar.gz
      verbose: true
    condition: and(startsWith(variables['TAG'], 'v'), eq(variables['DEPLOY'], '1'))
  - task: GithubRelease@0
    displayName: Create GitHub Release
    inputs:
      githubConnection: github.com_psibi
      assets: $(Build.ArtifactStagingDirectory)/tldr-linux-$(TAG).tar.gz
      assetUploadMode: replace
      action: edit
      tag: $(TAG)
    condition: and(startsWith(variables['TAG'], 'v'), eq(variables['DEPLOY'], '1'))
